WITH TOTAL AS (
    SELECT *
    FROM BOOK JOIN (SELECT BOOK_ID, SUM(SALES) AS TOTAL_SALES 
                    FROM BOOK_SALES 
                    WHERE TO_CHAR(SALES_DATE, 'YYYY-MM') = '2022-01'
                    GROUP BY BOOK_ID) USING(BOOK_ID) JOIN AUTHOR USING(AUTHOR_ID)
)
SELECT AUTHOR_ID, AUTHOR_NAME, CATEGORY, SUM(TOTAL_SALES * PRICE) AS TOTAL_SALES
FROM TOTAL
GROUP BY AUTHOR_ID, AUTHOR_NAME, CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC