WITH RECURSIVE TREE AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, T.GENERATION + 1
    FROM ECOLI_DATA E JOIN TREE T ON E.PARENT_ID = T.ID
)
SELECT ID
FROM TREE
WHERE GENERATION = 3
ORDER BY ID ASC