SELECT ITEM_ID, ITEM_NAME, RARITY
FROM ITEM_INFO
WHERE ITEM_ID IN (SELECT T.ITEM_ID
        FROM (SELECT *
        FROM ITEM_INFO
        WHERE RARITY = 'RARE') R JOIN ITEM_TREE T ON R.ITEM_ID = T.PARENT_ITEM_ID)
ORDER BY ITEM_ID DESC