SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS D, (SELECT NAME, CODE FROM SKILLCODES WHERE NAME = 'Python') P, (SELECT NAME, CODE FROM SKILLCODES WHERE NAME = 'C#') C
WHERE (D.SKILL_CODE & P.CODE) = P.CODE OR (SKILL_CODE & C.CODE) = C.CODE
ORDER BY ID ASC