WITH FISH_MAX AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
SELECT ID, FISH_NAME, LENGTH
FROM FISH_MAX JOIN FISH_INFO USING(FISH_TYPE, LENGTH) JOIN FISH_NAME_INFO USING(FISH_TYPE)
ORDER BY ID ASC
